title: "xut | Apuntes TryHackMe"
description: "Apuntes técnicos de ciberseguridad en castellano"
url: "https://xut-e.github.io"
baseurl: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - README.md
  - LICENSE
  - .github
  - assets
  - node_modules
  - vendor

